# Generated by Django 3.1.4 on 2021-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.BinaryField()),
                ('is_liked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'events_table',
            },
        ),
    ]
